let products = [
  {
    id: 1,
    name: 'Almohada Belmo Memory Foam',
    color: 'white',
    size: '50X70',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo atque dolor unde incidunt harum perspiciatis similique, voluptate sed aspernatur voluptates.',
    image: ['https://www.pillowtop.com.ar/wp-content/uploads/belmo-memoryfoam-1.jpg', 'https://www.pillowtop.com.ar/wp-content/uploads/belmo-memoryfoam2-1.jpg'],
    stock: 5,
    price: 3200,
  },
  {
    id: 2,
    name: 'Almohada Cannon Viscoelástica',
    color: 'white',
    size: 'null',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo atque dolor unde incidunt harum perspiciatis similique, voluptate sed aspernatur voluptates.',
    image: ['https://www.pillowtop.com.ar/wp-content/uploads/cannon-visco.png'],
    stock: 1,
    price: 4500,
  },
  {
    id: 3,
    name: 'Almohada Cannon Viscoelástica Cervical',
    color: 'white',
    size: 'null',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo atque dolor unde incidunt harum perspiciatis similique, voluptate sed aspernatur voluptates.',
    image: ['https://www.pillowtop.com.ar/wp-content/uploads/cannonalmohada.jpg'],
    stock: 3,
    price: 4500,
  },
  {
    id: 4,
    name: 'Almohada Nativa Triangular',
    color: 'white',
    size: '35X35',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo atque dolor unde incidunt harum perspiciatis similique, voluptate sed aspernatur voluptates.',
    image: ['https://www.pillowtop.com.ar/wp-content/uploads/triangulo.jpg'],
    stock: 1,
    price: 1500,
  },
  {
    id: 5,
    name: 'Almohada Palette Cervical Viscoelástica',
    color: 'white',
    size: '40X60',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo atque dolor unde incidunt harum perspiciatis similique, voluptate sed aspernatur voluptates.',
    image: ['https://www.pillowtop.com.ar/wp-content/uploads/Palette-Viscosmart-Cervical.jpg', 'https://www.pillowtop.com.ar/wp-content/uploads/Palette-Viscosmart-Detalle.jpg'],
    stock: 5,
    price: 3200,
  },
  {
    id: 6,
    name: 'Almohada Palette Extra Firme',
    color: 'white',
    size: '50X70',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo atque dolor unde incidunt harum perspiciatis similique, voluptate sed aspernatur voluptates.',
    image: ['https://www.pillowtop.com.ar/wp-content/uploads/Palette-Boris-Urban-Extra-Firme.jpg'],
    stock: 0,
    price: 1380,
  },
  {
    id: 7,
    name: 'Almohada Palette Suave',
    color: 'white',
    size: '50X70',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo atque dolor unde incidunt harum perspiciatis similique, voluptate sed aspernatur voluptates.',
    image: ['https://www.pillowtop.com.ar/wp-content/uploads/Palette-Suave.jpg', 'https://www.pillowtop.com.ar/wp-content/uploads/Palette-Suave-Detalle.jpg'],
    stock: 0,
    price: 1400,
  },
  {
    id: 8,
    name: 'Almohada Palette Visco Smart',
    color: 'white',
    size: '40x60',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo atque dolor unde incidunt harum perspiciatis similique, voluptate sed aspernatur voluptates.',
    image: ['https://www.pillowtop.com.ar/wp-content/uploads/Palette-Viscosmart.jpg', 'https://www.pillowtop.com.ar/wp-content/uploads/Palette-Viscosmart-Detalle.png'],
    stock: 5,
    price: 3000,
  },
  {
    id: 9,
    name: 'Almohada Piero Cervical',
    color: 'white',
    size: '65x35',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo atque dolor unde incidunt harum perspiciatis similique, voluptate sed aspernatur voluptates.',
    image: ['https://www.pillowtop.com.ar/wp-content/uploads/almoha.png'],
    stock: 5,
    price: 2499,
  },
]

export default products
